### ISSUE TITLE
Getting `Uncaught Error` in console.

### ISSUE THREAD

**Issue by anil1712** [shellus/angular-MQTT#1]
Hi,
I am pretty new for MQTT and I integrated it as it is as per your instruction, It works first time but after some time I got below message in console.

<code>
angular-MQTT.js:32 Uncaught Error: received data can not parse for JSON !
</code>

**Comment by shellus** [comment]
see：https://github.com/shellus/angular-MQTT/blob/master/src/angular-MQTT.js  line: 30

this library try parse payload to json。

if payload data not json string . throws an exception.

so, You must confirm the received data must be json。

**Comment by anil1712** [comment]
Thanks for quick reply, so mean to say I have to publish the message in JSON format or I need to do this thing in angular side. Please give me some sample for reference link for this. Right now I am using MQTT Web Client UI for publishing the mesaage and using the angular for subscribing.

**Comment by shellus** [comment]
see: http://sentris.endaosi.com/

use javascript send data.

server only do proxy

I am Chinese, How about you?

**Comment by shellus** [comment]
server is mosquitto [http://mosquitto.org/](http://mosquitto.org/)

**Comment by shellus** [comment]
You can also go directly to the test using sentris.endaosi.com

**Comment by shellus** [comment]
If you use the discovery is not enough, you can try directly https://github.com/mqttjs/MQTT.js#browser

**Comment by anil1712** [comment]
Thanks for the resourse links.
I am Indian but with google help I translated into English. I am trying to apply the solutions.

**Comment by anil1712** [comment]
Hi,
How do we subscribe any topic by using your library?

**Comment by shellus** [comment]
see: https://github.com/shellus/angular-MQTT/blob/master/bower_components/angular-mqtt/index.html
line: 27

**Comment by anil1712** [comment]
Hi, I just found its not working inside my `http` success response block. Don't know whats happenning. Please help me to out of it. Just try and http call and subscribe for any topic. Code block not executed.

**Comment by anil1712** [comment]
OK Thanks for your help.

**Comment by jupazave** [comment]
@anil1712 I changed this in #3. In the MQTT standart you are not forced to use JSON as Payload.
