### ISSUE TITLE
How can I unsubscribe packets

### ISSUE THREAD

**Issue by ajeetku** [shellus/angular-MQTT#6]
Hello,
i am using this library, i have subscribe some packet  using `MQTTService.on()`. How can i unsubscribe or stop to get response from any previous packets.

**Comment by shellus** [comment]
请尝试使用：https://github.com/mqttjs/MQTT.js#browser

**Comment by austinemayer** [comment]
Hey @ajeetku so I recently had the same problem. So I scrubbed through the mqtt library and found that you can close the connection. Maybe this will help you.
`    
service.close = function(){
      client.end();
    }
`

**Comment by ajeetku** [comment]
Thanks @austinemayer, your reply yes its work
I have added this inside angular-MQTT.js after Service.send funtion
like this:
Service.drop = function(name){
                callbacks[name] = "";
                client.unsubscribe(name);
            };
its working perfectly.
